base:
  base_scale: 0.0000305
  base_shift: 0.1378
  batch_size: 16
  image_size: [384, 384]
  excluded_files:
    - dish_1558109714
    - dish_1557861837
    - dish_1558031675
    - dish_1564159636
    - dish_1558029518
    - dish_1557862384
    - dish_1556572657
    - dish_1558109511

train:
  base_lr: 0.00001
  max_lr: 0.0001
  num_epochs: 100
  num_workers: 2
  model_path: '/content/DPT/weights/dpt_hybrid-midas-501f0c75.pt'
  weights_save_path: '/content/drive/Shareddrives/Food Analytic/models/DPT/'
  logs_save_path: '/content/drive/Shareddrives/Food Analytic/models/DPT/'
  checkpoint_path: None
